# This file is machine-generated - editing it directly is not advised

julia_version = "1.12.4"
manifest_format = "2.0"
project_hash = "0d23bee03300ed07e5dec96819eb0518153addb1"

[[deps.Jsubmit]]
path = "."
uuid = "4fec4833-94a8-4ec6-b1ec-1b26e595b69f"
version = "1.0.0-DEV"
